;this file for FamiTone2 library generated by text2data tool

The_Ordinary_Road_music_data:
	db 1
	dw @instruments
	dw @samples-3
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,344,286

@instruments:
	db $30 ;instrument $00
	dw @env6,@env0,@env0
	db $00
	db $b0 ;instrument $01
	dw @env4,@env0,@env0
	db $00
	db $70 ;instrument $02
	dw @env1,@env0,@env10
	db $00
	db $30 ;instrument $03
	dw @env2,@env7,@env0
	db $00
	db $30 ;instrument $05
	dw @env3,@env8,@env0
	db $00
	db $30 ;instrument $06
	dw @env5,@env9,@env0
	db $00

@samples:
@env0:
	db $c0,$00,$00
@env1:
	db $cf,$cd,$cb,$c9,$00,$03
@env2:
	db $c4,$c5,$c2,$c1,$c0,$00,$04
@env3:
	db $ca,$c8,$c7,$c6,$c5,$c4,$c4,$c3,$c3,$c2,$02,$c1,$c1,$c0,$00,$0d
@env4:
	db $cc,$ca,$c8,$c6,$00,$03
@env5:
	db $c8,$c6,$c4,$c1,$c0,$00,$04
@env6:
	db $cf,$00,$00
@env7:
	db $be,$c0,$00,$01
@env8:
	db $c1,$b8,$be,$bf,$c0,$00,$04
@env9:
	db $d2,$c6,$c0,$00,$02
@env10:
	db $c3,$c3,$c0,$c0,$bf,$bf,$be,$be,$c1,$02,$be,$be,$00,$07


@song0ch0:
	db $fb,$06
@song0ch0loop:
@ref0:
	db $82,$26,$85,$3e,$85,$4c,$85,$44,$85,$1e,$85,$36,$85,$4e,$85,$44
	db $85,$2c,$85,$44,$85,$4c,$85,$44,$85,$42,$85,$44,$85,$48,$85,$3a
	db $85
@ref1:
	db $26,$85,$3e,$85,$4c,$85,$44,$85,$1e,$85,$36,$85,$4e,$85,$44,$85
	db $2c,$85,$44,$85,$4c,$85,$44,$85,$42,$85,$44,$85,$48,$85,$3a,$85
	db $ff,$20
	dw @ref1
	db $ff,$20
	dw @ref1
	db $ff,$20
	dw @ref1
	db $ff,$20
	dw @ref1
	db $ff,$20
	dw @ref1
	db $ff,$20
	dw @ref1
	db $ff,$20
	dw @ref1
@ref9:
	db $26,$85,$3e,$85,$4c,$85,$44,$85,$1e,$85,$36,$85,$4e,$85,$44,$85
	db $2c,$85,$44,$85,$00,$ad
	db $fd
	dw @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref10:
	db $f9,$85
@ref11:
	db $f9,$85
@ref12:
	db $87,$84,$4d,$01,$4d,$01,$56,$00,$56,$85,$01,$45,$01,$45,$01,$4c
	db $00,$4c,$8d,$00,$b1
@ref13:
	db $87,$4d,$01,$4d,$01,$56,$00,$56,$85,$01,$52,$00,$52,$89,$01,$4e
	db $00,$4c,$8d,$00,$ad
@ref14:
	db $87,$4d,$01,$4d,$01,$56,$89,$01,$45,$01,$45,$01,$4c,$91,$00,$b1
@ref15:
	db $87,$4d,$01,$4d,$01,$45,$01,$4f,$01,$4e,$00,$4f,$01,$4c,$85,$01
	db $44,$8d,$00,$ad
@ref16:
	db $87,$4d,$01,$4d,$01,$56,$00,$56,$85,$01,$45,$01,$45,$01,$4c,$00
	db $4c,$8d,$00,$b1
	db $ff,$15
	dw @ref13
	db $ff,$10
	dw @ref14
	db $ff,$14
	dw @ref15
	db $fd
	dw @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref20:
	db $80,$26,$99,$01,$2c,$99,$01,$2c,$99,$01,$22,$99,$00,$81
@ref21:
	db $26,$99,$01,$2c,$99,$01,$2c,$99,$01,$22,$99,$00,$81
	db $ff,$0d
	dw @ref21
	db $ff,$0d
	dw @ref21
	db $ff,$0d
	dw @ref21
	db $ff,$0d
	dw @ref21
	db $ff,$0d
	dw @ref21
	db $ff,$0d
	dw @ref21
	db $ff,$0d
	dw @ref21
@ref29:
	db $26,$99,$01,$2c,$99,$01,$2c,$8d,$00,$ad
	db $fd
	dw @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref30:
	db $f9,$85
@ref31:
	db $f9,$85
@ref32:
	db $f9,$85
@ref33:
	db $f9,$85
@ref34:
	db $f9,$85
@ref35:
	db $f9,$85
@ref36:
	db $8a,$08,$85,$86,$1e,$85,$88,$1a,$85,$86,$1e,$85,$8a,$09,$09,$86
	db $1e,$85,$88,$1a,$85,$86,$1e,$85,$8a,$08,$85,$86,$1e,$85,$88,$1a
	db $85,$86,$1f,$17,$1f,$17,$10,$85,$88,$1a,$85,$86,$1e,$85
	db $ff,$20
	dw @ref36
	db $ff,$20
	dw @ref36
@ref39:
	db $8a,$08,$85,$86,$1e,$85,$88,$1a,$85,$86,$1e,$85,$8a,$09,$09,$86
	db $1e,$85,$88,$1a,$85,$86,$1e,$85,$8a,$08,$85,$86,$1e,$85,$00,$ad
	db $fd
	dw @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref40:
	db $f9,$85
@ref41:
	db $f9,$85
@ref42:
	db $f9,$85
@ref43:
	db $f9,$85
@ref44:
	db $f9,$85
@ref45:
	db $f9,$85
@ref46:
	db $f9,$85
@ref47:
	db $f9,$85
@ref48:
	db $f9,$85
@ref49:
	db $f9,$85
	db $fd
	dw @song0ch4loop
